# Generated by Django 3.2.3 on 2021-05-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('S', 'Classe S'), ('A', 'Classe A'), ('B', 'Classe B'), ('C', 'Classe C')], default='C', max_length=2)),
                ('original_location', models.CharField(max_length=50)),
                ('current_location', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
