# Generated by Django 3.2.3 on 2021-06-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='isActive',
            new_name='inBattle',
        ),
    ]
