# Generated by Django 3.2.9 on 2021-12-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_rename_isactive_hero_inbattle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='original_location',
        ),
    ]
